version: '3.8'

services:
  nextjs:
    build:
      context: ./frontend/nextjs-app
      dockerfile: Dockerfile
    container_name: teknofest-nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_SOCKET_URL=ws://backend:8000
    depends_on:
      - backend
      - redis
      - postgres
    networks:
      - teknofest-network
    volumes:
      - nextjs-cache:/app/.next/cache
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: teknofest-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://teknofest:teknofest2025@postgres:5432/teknofest_db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
    depends_on:
      - redis
      - postgres
    networks:
      - teknofest-network
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: teknofest-redis
    ports:
      - "6379:6379"
    networks:
      - teknofest-network
    volumes:
      - redis-data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: teknofest-postgres
    environment:
      - POSTGRES_USER=teknofest
      - POSTGRES_PASSWORD=teknofest2025
      - POSTGRES_DB=teknofest_db
    ports:
      - "5432:5432"
    networks:
      - teknofest-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: teknofest-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.nextjs.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - nextjs
      - backend
    networks:
      - teknofest-network
    restart: unless-stopped

networks:
  teknofest-network:
    driver: bridge

volumes:
  nextjs-cache:
  redis-data:
  postgres-data: