modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: "ip4"
      valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
      valid_status_codes: [200, 201, 202, 203, 204, 301, 302, 303, 304, 307, 308]
      method: GET
      follow_redirects: true
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: false
  
  http_post_2xx:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: "ip4"
      valid_status_codes: [200, 201, 202, 204]
      method: POST
      headers:
        Content-Type: application/json
      body: '{"test": true}'
  
  http_401:
    prober: http
    timeout: 5s
    http:
      valid_status_codes: [401]
      method: GET
  
  http_health:
    prober: http
    timeout: 5s
    http:
      preferred_ip_protocol: "ip4"
      valid_status_codes: [200]
      method: GET
      path: /health
  
  tcp_connect:
    prober: tcp
    timeout: 5s
  
  dns_check:
    prober: dns
    timeout: 5s
    dns:
      preferred_ip_protocol: "ip4"
      query_name: "teknofest2025.com"
      query_type: "A"
  
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
      preferred_ip_protocol: "ip4"
  
  grpc:
    prober: grpc
    timeout: 5s
    grpc:
      tls: false
      preferred_ip_protocol: "ip4"
  
  grpc_tls:
    prober: grpc
    timeout: 5s
    grpc:
      tls: true
      preferred_ip_protocol: "ip4"