groups:
  - name: system_alerts
    interval: 30s
    rules:
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected on {{ $labels.instance }}"
          description: "CPU usage is above 80% (current value: {{ $value }}%)"

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "High memory usage detected on {{ $labels.instance }}"
          description: "Memory usage is above 90% (current value: {{ $value }}%)"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 5m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space is below 10% (current value: {{ $value }}%)"

  - name: application_alerts
    interval: 30s
    rules:
      - alert: ServiceDown
        expr: up{job=~"backend|mcp-server|nginx"} == 0
        for: 1m
        labels:
          severity: critical
          service: application
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 1 minute"

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) by (job) > 0.05
        for: 5m
        labels:
          severity: warning
          service: application
        annotations:
          summary: "High error rate in {{ $labels.job }}"
          description: "Error rate is above 5% (current value: {{ $value }})"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, job)) > 1
        for: 5m
        labels:
          severity: warning
          service: application
        annotations:
          summary: "High response time in {{ $labels.job }}"
          description: "95th percentile response time is above 1s (current value: {{ $value }}s)"

      - alert: TooManyRequests
        expr: sum(rate(http_requests_total[1m])) by (job) > 1000
        for: 2m
        labels:
          severity: warning
          service: application
        annotations:
          summary: "High request rate in {{ $labels.job }}"
          description: "Request rate is above 1000 req/min (current value: {{ $value }})"

  - name: database_alerts
    interval: 30s
    rules:
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 1m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been down for more than 1 minute"

      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends{datname="teknofest"} / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "High number of database connections"
          description: "Database connection usage is above 80% (current: {{ $value }})"

      - alert: DatabaseReplicationLag
        expr: pg_replication_lag > 10
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "High database replication lag"
          description: "Replication lag is above 10 seconds (current: {{ $value }}s)"

      - alert: SlowQueries
        expr: rate(pg_stat_database_blks_hit[5m]) < 0.9
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "Database cache hit ratio is low"
          description: "Cache hit ratio is below 90% (current: {{ $value }})"

  - name: redis_alerts
    interval: 30s
    rules:
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
          service: cache
        annotations:
          summary: "Redis is down"
          description: "Redis cache has been down for more than 1 minute"

      - alert: RedisHighMemory
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: "Redis memory usage is high"
          description: "Redis memory usage is above 90% (current: {{ $value }})"

      - alert: RedisRejectedConnections
        expr: rate(redis_rejected_connections_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: "Redis is rejecting connections"
          description: "Redis has rejected {{ $value }} connections in the last 5 minutes"

  - name: security_alerts
    interval: 30s
    rules:
      - alert: PossibleDDoS
        expr: sum(rate(http_requests_total[1m])) by (client_ip) > 100
        for: 2m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Possible DDoS attack from {{ $labels.client_ip }}"
          description: "Client {{ $labels.client_ip }} is making {{ $value }} requests per minute"

      - alert: UnauthorizedAccess
        expr: sum(rate(http_requests_total{status="401"}[5m])) > 10
        for: 5m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "High number of unauthorized access attempts"
          description: "{{ $value }} unauthorized access attempts in the last 5 minutes"

      - alert: SuspiciousActivity
        expr: sum(rate(http_requests_total{path=~".*(\\.\\.|//|\\\\).*"}[5m])) > 0
        for: 1m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Suspicious path traversal attempts detected"
          description: "Potential path traversal attack detected"

  - name: business_alerts
    interval: 30s
    rules:
      - alert: LowUserEngagement
        expr: sum(rate(operation_learning_path_created_total[1h])) < 1
        for: 1h
        labels:
          severity: info
          service: business
        annotations:
          summary: "Low user engagement"
          description: "Less than 1 learning path created in the last hour"

      - alert: HighAIModelLatency
        expr: histogram_quantile(0.95, sum(rate(operation_model_inference_duration_seconds_bucket[5m])) by (le)) > 5
        for: 5m
        labels:
          severity: warning
          service: ai
        annotations:
          summary: "High AI model inference latency"
          description: "95th percentile model inference time is above 5s (current: {{ $value }}s)"

      - alert: ModelErrorRate
        expr: sum(rate(operation_model_inference_failure[5m])) / sum(rate(operation_model_inference_total[5m])) > 0.1
        for: 5m
        labels:
          severity: warning
          service: ai
        annotations:
          summary: "High AI model error rate"
          description: "Model error rate is above 10% (current: {{ $value }})"