# TEKNOFEST 2025 - Eğitim Teknolojileri Eylemcisi
# Ana Konfigürasyon Dosyası

project:
  name: "TEKNOFEST 2025 Eğitim Eylemcisi"
  version: "0.1.0"
  description: "Kişiselleştirilmiş Türkçe eğitim asistanı"

# Model ayarları
model:
  base_model: "Qwen/Qwen2-7B"
  language: "tr"
  max_length: 2048
  temperature: 0.7
  
# Öğrenme ayarları
learning:
  styles: ["visual", "auditory", "reading", "kinesthetic"]
  grade_levels: [9, 10, 11, 12]
  subjects:
    - matematik
    - fizik
    - kimya
    - biyoloji
    - türkçe
    - tarih
    - coğrafya
    
# Agent ayarları
agents:
  learning_path:
    enabled: true
    zpd_threshold: 0.15
    
  study_buddy:
    enabled: true
    response_style: "friendly"
    
  accessibility:
    enabled: true
    features:
      - text_to_speech
      - font_size_adjustment
      - high_contrast

# Veri kaynakları
data_sources:
  eba:
    enabled: true
    api_url: "https://eba.gov.tr/api"
    
# Logging
logging:
  level: "INFO"
  file: "logs/app.log"